version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency update"
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 20
    rebase-strategy: "auto"
    reviewers:
      - "asadali214"
